name: Update leaderboards using GitHub Actions 🥇
run-name: ${{ github.actor }} triggered a leaderboard update using GitHub Actions 🏆
on:
  push:
    branches:
      - main

jobs:
  Update-Leaderboards:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # Checkout the repository content to github runner.

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: "**/optimized_agent.dill"

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9 # Install the python needed

      - name: Install Reinforcelab
        run: python -m pip install -e .

      - name: Install Dependencies
        run: python -m pip install --upgrade pip datetime dill numpy pandas tabulate # Common for all environments

      # Runs a set of commands using the runners shell
      - name: Update README.md leaderboards
        run: |
          python leaderboard_bot/update_leaderboards.py ${{ steps.changed-files.outputs.all_changed_files }} ${{ github.actor }}
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git pull
          git status
          git add .
          git commit -am "Automated report"
          git push
